### ISSUE TITLE
Events not being fired

### ISSUE THREAD

**Issue by gaurishhs** [reinhello/eris-giveaways#19]
Hi, I'm using this package for my bot and i notice that no event is being fired,

https://user-images.githubusercontent.com/78847111/183583898-8cdd8605-53e0-4bd1-b240-f83a6f44df54.mov

**Comment by reinhello** [comment]
Do you have `guildMessageReactions` intent enabled?

**Comment by gaurishhs** [comment]
Yes, I have all the intents enabled

**Comment by reinhello** [comment]
I'll have a look at the code.

**Comment by gaurishhs** [comment]
@reinhello Hi! I also noticed that `timestamp` is not being replaced 
https://discord-giveaways.js.org/global.html#GiveawayMessages
![Screenshot 2022-08-09 at 6 56 03 PM](https://user-images.githubusercontent.com/78847111/183658319-b43e4229-cae2-4c5c-a466-f43a3f6c5394.png)

![Screenshot 2022-08-09 at 6 55 35 PM](https://user-images.githubusercontent.com/78847111/183658214-e7292206-925d-482e-b440-02dfded92963.png)

**Comment by reinhello** [comment]
@gaurishhs As I remembered, it was actually `{duration}`, not `{timestamp}`

**Comment by gaurishhs** [comment]
Yes, That seems to work. 

Also, Can't we change the giveaway embed title? `discord-giveaways` supports that

**Comment by gaurishhs** [comment]
@reinhello I feel as if something is really wrong with the lib, `exemptMembers` too isn't working, 

```ts
exemptMembers: async (member) => {
          return member.roles.includes(roleID);
        }
 ```

**Comment by reinhello** [comment]
> @reinhello I feel as if something is really wrong with the lib if not the lib then definetly it is at my side but i have the reactions intent enabled, `exemptMembers` too isn't working,
> 
> ```ts
> exemptMembers: async (member) => {
>           return member.roles.includes(roleID);
>         }
> ```
> 
> I have my client as such:
> 
> ```ts
> const client = new Client(
>  'Bot TOKEN_HERE',
>  {
>    restMode: true,
>    intents: ['all']
>  }
> );
> ```

Can you open a separate issue for this? I'll investigate the issue further when I had time to or you can open a pull request if you find any solutions already.

**Comment by gaurishhs** [comment]
Sure thing
